### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by nicolastobo** [chargebee/chargebee-python#10]
```
    from chargebee import request
  File "/Users/nico/Projects/nouma/bo/venv/lib/python3.5/site-packages/chargebee/request.py", line 10
    if isinstance(v, (list)):
                            ^
TabError: inconsistent use of tabs and spaces in indentation
```

<img width="513" alt="capture d ecran 2016-05-20 a 15 12 25" src="https://cloud.githubusercontent.com/assets/568565/15428737/7502e0e0-1e9d-11e6-83ec-5d358e490390.png">

I use the last version available via pip (2.0.4)

**Comment by vaibhav1510** [comment]
Hi Nicolas,

We are working on the fix. Will keep you posted. Thanks

**Comment by vaibhav1510** [comment]
Nicolas,

We have removed the error prone version. Please update the package to latest version 2.0.5. 

Let us know if you have any queries. 
Thanks

**Comment by nicolastobo** [comment]
Thanks for your reactivity !
