### ISSUE TITLE
Move from urllib to requests

### ISSUE THREAD

**Issue by josericardo** [chargebee/chargebee-python#15]
Hi, I see the lib uses urllib. Would you be open to a switch to requests (https://github.com/request/request)?

Besides the nice api, if chargebee-python used requests it could benefit from other nice libraries like:

- requests cache https://pypi.python.org/pypi/requests-cache
- vcrpy https://github.com/kevin1024/vcrpy (which doesn't support urllib, unfortunately)

Thoughts?

**Comment by cosmith** [comment]
+1 on the migration, spent the whole day trying to figure out why my tests were failing with VCRpy and Chargebee before finding this issue

**Comment by cb-goutham** [comment]
This has been addressed in v2.8.4
