### ISSUE TITLE
Don't distribute the tests package

### ISSUE THREAD

**Issue by dschep** [chargebee/chargebee-python#17]
You probably shouldn't distribute the tests package as no one expects to get a package by that name when they `pip install chargebee`. [Just exclude it](http://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages):

```
find_packages(exclude=["tests"])
```

**Comment by Christoph-Schabert** [comment]
There is a mr open for this since months.

https://github.com/chargebee/chargebee-python/pull/18

**Comment by rcoup** [comment]
This seems fixed? #18 was merged
