### ISSUE TITLE
AttributeError: type object 'Export' has no attribute 'invoices'

### ISSUE THREAD

**Issue by gliv** [chargebee/chargebee-python#28]
Following the docs, I am supposed to be able to retrieve invoices, subscriptions, transcations... for example: https://apidocs.chargebee.com/docs/api/exports#export_invoices

However, when I try to do that, I get:

```
result = chargebee.Export.invoices({
AttributeError: type object 'Export' has no attribute 'invoices'
```

Looking at https://github.com/chargebee/chargebee-python/blob/master/chargebee/models/export.py that seems true.

Is the doc ahead of the client? Or am I missing something here?

**Comment by cb-rakesh** [comment]
Can you confirm if the issue still persists with the latest release version. Or else we can close this.
