### ISSUE TITLE
Allow setting timeouts for http requests

### ISSUE THREAD

**Issue by ashwini-balnaves** [chargebee/chargebee-python#30]
I would like to be able to set a timeout for requests being sent to chargebee. I am happy to make a pull request to enable this behaviour. I can see two ways to go here:

1. Add a timeout to the `Environment` class in `environment.py` so that it can be set during `chargebee.configure`.

2. Add a keyword parameter to methods that use `request.send` and `request.send_list_request` which will get eventually passed to the connection object. This means that the timeout can be configurable per api call.

Are either of these options acceptable? Again, I am happy to submit a pull request if the project is happy to proceed with this feature request.

**Comment by cb-prajaktachavan** [comment]
This has been merged in v2.11.0. You can set own http connect and read timeouts using chargebee.update_connect_timeout_secs() and chargebee.update_read_timeout_secs().
