### ISSUE TITLE
Lack of SNI support

### ISSUE THREAD

**Issue by jap** [chargebee/chargebee-python#39]
This library doesn't put SNI when it connects to perform API requests. Doing so however is good practice.
Note that there were some releases of docker desktop for mac recently that shipped with a transparant proxy in it, that only was able to forward connections using SNI, breaking this code. This has been fixed now on the docker side. (see also https://github.com/docker/for-mac/issues/5568)
A fix is waiting for you at https://github.com/chargebee/chargebee-python/pull/38 .

**Comment by cb-khushbubibay** [comment]
This issue has been obsoleted since release 2.8.4, which uses requests, so closing this Issue.
