### ISSUE TITLE
How to enable Google Analytics (GA4) from the API?

### ISSUE THREAD

**Issue by mbreuker** [chargebee/chargebee-python#55]
In the documentation on https://www.chargebee.com/docs/2.0/ga-inapp-checkout.html it's is described how to enable GA for the Checkout Portal:

You need to 'Pass the enableGATracking parameter as true when initializing the Chargebee instance.':

`var chargebeeInstance = Chargebee.init({
    site: "your-chargebee-subdomain",
    enableGATracking: true
});`

But how can I do this using the Python SDK? The method chargebee.configure() only allows me to set site and api_key.

Thanks,

Mark

**Comment by cb-bharathvaj** [comment]
@mbreuker GTM is only supported when the checkout is opened via ChargebeeJS client side library and not by our server side SDKs.
