### ISSUE TITLE
Possibility to instantiate Chargebee clients

### ISSUE THREAD

**Issue by rdn1337** [chargebee/chargebee-python#57]
I have a case where I need to work with two different Chargebee account in the same SaaS application.

If I’m not mistaken, the Chargebee configuration is currently “global”. I currently workaround this issue by updating the configuration before each call with the proper credentials but I suspect I’ll run into race-condition issues at scale.

I know some 3rd-party librairies allow to configure multiple client instances, would it be applicable for this library? Do you have any other suggestions?

**Comment by cb-bharathvaj** [comment]
It is possible to pass site and api keys at request levels to support multiple sites. https://apidocs.chargebee.com/docs/api/auth
