### ISSUE TITLE
APIError init fails in models/event.py line 20

### ISSUE THREAD

**Issue by kunalg** [chargebee/chargebee-python#6]
```APIError.__init__()``` takes two params (apart from self):
https://github.com/chargebee/chargebee-python/blob/master/chargebee/api_error.py#L3

However, on models/event.py line 20, it's passed only a string message.
https://github.com/chargebee/chargebee-python/blob/master/chargebee/models/event.py#L20

This throws a TypeError saying ```'__init__()``` takes 3 arguments (2 given)'

Example:
```python
>>> import chargebee
>>> data = 'non-json-data'
>>> chargebee.Event.deserialize(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kunal/work/kunal/python/chargebee/local/lib/python2.7/site-packages/chargebee/models/event.py", line 20, in deserialize
    raise APIError("Invalid webhook object to deserialize")
TypeError: __init__() takes exactly 3 arguments (2 given)
```

**Comment by vaibhav1510** [comment]
Hi Kunal, we have released the fix for this.
